import path from 'path';
import { MCPConfig, MCPTool, DetectedConfig } from '../types';

/**
 * Build an MCP configuration from scanned tools
 */
export async function buildMCPConfig(
  projectPath: string,
  tools: MCPTool[]
): Promise<MCPConfig> {
  const projectName = path.basename(projectPath);
  const serverName = `${projectName}-server`;

  // Determine the command to run based on detected config
  const { command, args } = await determineServerCommand(projectPath);

  return {
    serverName,
    tools,
    command,
    args,
    env: {
      PROJECT_PATH: projectPath,
    },
  };
}

/**
 * Determine the command and args to run the MCP server
 */
async function determineServerCommand(
  projectPath: string
): Promise<{ command: string; args: string[] }> {
  // Check for existing MCP server setup
  const fs = await import('fs-extra');

  // Look for package.json with mcp script
  const packageJsonPath = path.join(projectPath, 'package.json');
  if (await fs.pathExists(packageJsonPath)) {
    try {
      const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));

      if (packageJson.scripts?.mcp) {
        return {
          command: 'npm',
          args: ['run', 'mcp'],
        };
      }

      if (packageJson.scripts?.start) {
        return {
          command: 'npm',
          args: ['run', 'start'],
        };
      }
    } catch {
      // Continue to next check
    }
  }

  // Look for Python with mcp module
  const mcpPyPath = path.join(projectPath, 'mcp_server.py');
  if (await fs.pathExists(mcpPyPath)) {
    return {
      command: 'python',
      args: ['mcp_server.py'],
    };
  }

  // Default: use node with a generated server
  return {
    command: 'node',
    args: ['-e', 'console.log("MCP server placeholder")'],
  };
}

/**
 * Generate a basic MCP server template for a project
 */
export function generateMCPServerTemplate(
  projectName: string,
  tools: MCPTool[]
): string {
  return `/**
 * Auto-generated MCP Server for ${projectName}
 * Generated by repo-emulator
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// Tool definitions
const tools = ${JSON.stringify(tools, null, 2)};

// Create server
const server = new Server(
  {
    name: '${projectName}-server',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Handle list tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: tools.map(tool => ({
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema,
    })),
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  const tool = tools.find(t => t.name === name);
  if (!tool) {
    throw new Error(\`Unknown tool: \${name}\`);
  }

  // TODO: Implement actual tool execution logic
  // This is a placeholder - you'll need to implement the actual function calls
  console.log(\`Executing tool: \${name}\`, args);

  return {
    content: [
      {
        type: 'text',
        text: \`Tool \${name} executed successfully\`,
      },
    ],
  };
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('${projectName} MCP server running on stdio');
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
`;
}

/**
 * Generate a Python MCP server template
 */
export function generatePythonMCPServerTemplate(
  projectName: string,
  tools: MCPTool[]
): string {
  return `"""
Auto-generated MCP Server for ${projectName}
Generated by repo-emulator
"""

import asyncio
import json
from typing import Any

# Tool definitions
TOOLS = ${JSON.stringify(tools, null, 2)}


async def handle_list_tools():
    """Handle list tools request."""
    return {
        "tools": [
            {
                "name": tool["name"],
                "description": tool["description"],
                "inputSchema": tool["inputSchema"],
            }
            for tool in TOOLS
        ]
    }


async def handle_call_tool(name: str, arguments: dict[str, Any]):
    """Handle tool call request."""
    # TODO: Implement actual tool execution logic
    print(f"Executing tool: {name}", arguments)

    return {
        "content": [
            {
                "type": "text",
                "text": f"Tool {name} executed successfully",
            }
        ]
    }


async def main():
    """Main server loop."""
    print(f"${projectName} MCP server starting...", flush=True)

    # Read requests from stdin
    while True:
        line = await asyncio.get_event_loop().run_in_executor(None, input)
        if not line:
            break

        try:
            request = json.loads(line)
            method = request.get("method")

            if method == "tools/list":
                response = await handle_list_tools()
            elif method == "tools/call":
                params = request.get("params", {})
                response = await handle_call_tool(
                    params.get("name"),
                    params.get("arguments", {})
                )
            else:
                response = {"error": "Unknown method"}

            print(json.dumps(response), flush=True)
        except Exception as e:
            print(json.dumps({"error": str(e)}), flush=True)


if __name__ == "__main__":
    asyncio.run(main())
`;
}

// Export builder as a class for consistency
export class MCPConfigBuilder {
  async build(projectPath: string, tools: MCPTool[]): Promise<MCPConfig> {
    return buildMCPConfig(projectPath, tools);
  }

  generateTemplate(projectName: string, tools: MCPTool[], language: 'ts' | 'py' = 'ts'): string {
    if (language === 'py') {
      return generatePythonMCPServerTemplate(projectName, tools);
    }
    return generateMCPServerTemplate(projectName, tools);
  }
}
